name: Run build
on:
  workflow_dispatch:
    inputs:
      major:
        type: string
        required: true
        description: Major version number
      minor:
        type: string
        required: true
        description: Minor version number
      patch:
        type: string
        required: true
        description: Patch version number
env:
  TARGET_VERSION: v${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
jobs:
  version_update:
    runs-on: ubuntu-latest
    name: Version Update to ${{ env.TARGET_VERSION }}
    steps:
      - run: |
          echo "${{ env.TARGET_VERSION }}"
  release:
    runs-on: ubuntu-latest
    name: Release
    needs: version_update
    steps:
      - run: |
          echo "${{ env.TARGET_VERSION }}"
