name: Release
on:
  workflow_dispatch:
    inputs:
      major:
        type: string
        required: true
        description: Major version number
      minor:
        type: string
        required: true
        description: Minor version number
      patch:
        type: string
        required: true
        description: Patch version number
env:
  TARGET_VERSION: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
jobs:
  version_update:
    runs-on: ubuntu-latest
    name: Version Update
    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install xmlstarlet
      - name: checkout
        uses: actions/checkout@v3
      - name: Update package version
        run: |
          find . -type f -name package.xml | \
          xargs -n 1 -I {} \
          xmlstarlet edit --inplace --pf \
          --update "//package/version" \
          --value ${{ env.TARGET_VERSION }} {}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ env.TARGET_VERSION }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: version_update
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create release
        run: |
          gh release create v{{ env.TARGET_VERSION }} -d -p --generate-notes
          gh release v{{ env.TARGET_VERSION }}
