name: Release
on:
  workflow_dispatch:
    inputs:
      fragment:
        type: choice
        description: Semantic version target
        options:
          - bug
          - feature
          - major
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install xmlstarlet
      - name: Get current version
        id: get_current_version
        run: |
          current_version=`\
            find . -name "package.xml" -print -quit \
            | xargs -n 1 -I{} \
            xmlstarlet select --template --value-of "//package/version" {}`
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.get_current_version.outputs.current_version }}
          version-fragment: ${{ github.event.inputs.fragment }}
      - name: Show
        run: |
          echo
      - name: Update package version
        run: |
          find . -type f -name package.xml | \
            xargs -n 1 -I {} \
            xmlstarlet edit --inplace --pf \
            --update "//package/version" \
            --value ${{ steps.bump_version.outputs.next-version }} {}
      - name: Create release
        run: |
          gh release create \
            v${{ steps.bump_version.outputs.next-version }} \
            -d -p --generate-notes
