name: Release
on:
  workflow_dispatch:
    inputs:
      major:
        type: string
        required: true
        description: Major version number
      minor:
        type: string
        required: true
        description: Minor version number
      patch:
        type: string
        required: true
        description: Patch version number
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_VERSION: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Update package version
        run: |
          find src -type f -name package.xml | \
          xargs -n 1 -I {} \
          xmlstarlet edit --inplace --pf \
          --update "//package/version" \
          --value ${{ env.TARGET_VERSION }} {}
      - name: Create release
        run: |
          gh release create v${{ env.TARGET_VERSION }} -d -p --generate-notes
          gh release upload v${{ env.TARGET_VERSION }}
