name: Release
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Semantic version target
        options:
          - major
          - feature
          - bug
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_VERSION: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install xmlstarlet
      - name: Get current version
        id: get_current_version
        run: |
          current_version=`\
            find . -name "package.xml" -print -quit \
            | xargs -n 1 -I{} \
            xmlstarlet select --template --value-of "//package/version" {}`
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
      - name: Show
        run: |
          echo ${{ steps.get_current_version.outputs.current_version }}
      - name: Update package version
        run: |
          find . -type f -name package.xml | \
          xargs -n 1 -I {} \
          xmlstarlet edit --inplace --pf \
          --update "//package/version" \
          --value ${{ env.TARGET_VERSION }} {}
      - name: Create release
        run: |
          gh release create v${{ env.TARGET_VERSION }} -d -p --generate-notes
